project_id = "rvqqnfsgovlxocjjugww"

[functions.invite-user]
verify_jwt = true

[functions.document-chat]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.community-assistant]
verify_jwt = false

[functions.generate-background]
verify_jwt = true

[functions.generate-photo-title]
verify_jwt = true
